# {targets}

The {targets} [documentation](https://docs.ropensci.org/targets/) and [help manual](https://books.ropensci.org/targets)
should be the first places to look for details on {targets}. We'll highlight some pages and links below relevant to the workshop, but be sure to spend time looking through these resources. This is a great example of an R package that has been very thoroughly and thoughtfully documented covering everything from beginner examples to the minutiae of how the package is designed and orchestrates workflows.

## [Help](https://books.ropensci.org/targets/help.html)

This help page is a great place to start when you are looking for help using {targets}. It details things to do before posting, and when you have decided to post a question, where to post it. The {targets} developer prefers using GitHub Discussion Groups for troubleshooting and discussions instead of GitHub Issues. 

### [GitHub Discussion Group](https://github.com/ropensci/targets/discussions)

{targets} has a very active discussion group with plenty of past solutions and discussions to search through when you are looking for help. 
This is the most complete guide to using {targets}. It has info on most of the questions that you will have (although can be complicated - be patient with yourself!). It explains [what a target is](https://books.ropensci.org/targets/targets.html), [best practices for functions](https://books.ropensci.org/targets/functions.html), and why [error messages can be less intuitive in your {targets} workflow](https://books.ropensci.org/targets/debugging.html) among many other things.

## [{targets} Overview Vignette](https://cran.r-project.org/web/packages/targets/vignettes/overview.html)

This vignette is an extremely high-level summary of the features of {targets}.

## [Intro Tutorial (by author of {targets})](https://wlandau.github.io/targets-tutorial/#1)

This slide deck was created for a intro to {targets} workshop by Will Landau - it gives some of the reasoning/justification for the creation and use of {targets}, and walks through a working example.

## [GitHub Discussion Group](https://github.com/ropensci/targets/discussions)

{targets} has a very active discussion group on GitHub! If you yourself have a question, there is a [guide](https://books.ropensci.org/targets/help.html) provided in the user manual to help you ask a relevant and answerable question

## [Data Science Example Workthrough](https://towardsdatascience.com/data-science-workflows-with-the-targets-package-in-r-end-to-end-example-with-code-1e31318074c4)

This workthrough is an example of building up a {targets} workflow (though it is not in our field).

## BONUS: [tarchetypes](https://docs.ropensci.org/tarchetypes/)

Even though {targets} itself has seemingly endless possibilities/flexibilities, tarchetypes extends that even further! Tarchetypes has functions that do complex tasks with simple syntax, making your life easier! `tar_file_read()`, `tar_render()`, and `tar_group_by()` are some really great ones to get started with.

## [tarchetypes GitHub Discussion Group](https://github.com/ropensci/tarchetypes/discussions)

Similar to {targets}, tarchetypes has a very active discussion group on GitHub!
