# {targets}: usage

## `tar_visnetwork()`


### Exercise: `tar_visnetwork()`



also see `tar_glimpse()`, `tar_mermaid()`, `tar_network()`


## `tar_make()`

isolated environment



Extra

could also make run distributed locally, with {future}, with {clustermq}
https://docs.ropensci.org/targets/reference/tar_make_future.html
https://docs.ropensci.org/targets/reference/tar_make_clustermq.html


### Exercise: `tar_make()`


## `tar_read()`, `tar_load()`


### Exercise: `tar_read()`, `tar_load()`


## Edits, rerun, edits, ... 

The approach now that we have a {targets} workflow setup is a bit different than you might be used to using R interactively. With a {targets} workflow, everything is defined in the workflow so our process is now about making edits to our functions and our `_targets.R` workflow, then rerunning `tar_make()`, making edits, ... 


### Exercise: practice the {targets} approach

Instruction: Make an edit, run tar_make, look at results, make an edit, run tar make

TODO where to look at results
