# Exercises: Projects

## RStudio Project Setup

We are going to set up an RStudio Project that we will use for the rest of this workshop. Please follow along with these steps and remember, if you are lost use your red sticky note or raise your hand and someone will come help you.

1.  Open RStudio and navigate to the upper right hand corner
2.  Click on the drop-down menu and select the first option: "New Project..."
    -   Alternatively, navigate to the top left corner, click "File", and then click "New Project..."
3.  Select "New Directory", then "New Project"
4.  Name the directory "2023-CSEE-workshop-projects" and navigate to the subdirectory in your computer where you want the folder to appear
5.  Minimize RStudio and using your file navigation system, navigate to the place on the computer where your project is saved (e.g., Downloads)
6.  Open the folder (you should see one file in there, an .Rproj file with the name you gave the folder)
    -   Create five folders within your project folder:

        -   raw-data

        -   output

        -   graphics

        -   scripts

        -   R
7.  Download the data from this [link](https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-pal.34.7&entityid=0fccb4e99aaa0c0cc85c23284288ec81) and move it into the `raw-data/` folder
8.  Open your project in RStudio
9.  Open an empty R script and save it as "README.md"
10. Fill in your README file with answers to the [Data Reuse Plan](https://github.com/mozillascience/working-open-workshop/blob/gh-pages/handouts/data_reuse_plan_template.md):

::: callout-note
There are many questions you may not have the answers to for this exercise - either make them up or ignore them! Do your best to answer what you can (while thinking about how you may alter/use this format in your own life/projects)
:::

**Description (abstract):** What is your project about? What is the goal? Why are you doing it? How does this data relate to your project?

**Title:** What do you want to call your data set?

**Permanent Identifier:** A way for folks to find your data. Do you have a DOI or other permanent identifier?

**Data Source:** If you included someone else's data in your data set, provide information on where it came from. Just like articles, if you use it, cite it. It is preferable to include a permanent identifier like a DOI.

**Subject:** In what discipline or subject area is your project?

**Related publication:** Have you published an article, thesis or some other publication based on this data? Include a full citation and permanent identifier, if available.

**Data Collector:** Person/organization responsible for collecting data

**Funder Information** : Is this project sponsored by a funding agency? If so, include name of the funding agency, grant number, and principal investigator name/s & affiliations.

**Collaborators:** Are there any collaborators on this project? Provide names and affiliations.

**Contact person:** Who should someone contact for additional information about the data set? Include affiliation and contact information such as phone number, email, and/or physical address.

**Location:** Where was the data collected? One place? Multiple places? Use geographic coordinates if appropriate.

**Place of publication:** Where is the data made publicly available? Include URL.

**Temporal Coverage:** When was the data collected? On a specific date? Specific time? Over a range of dates? Use the international standard date format (YYYY-MM-DD hh:mm.ss) and try to be as specific as possible.

**Publication Date:** When was the data made available in the place of publication (above)? Again, use the international standard date format.

**Data collection process:** What instruments were used to collect the data? how frequently were the data collected? how were data collection sites selected? if there was a sample population, how was it selected?

**Data processing:** How did you clean the data? how are missing or null values handled? did you write code for processing the data and where can it be found?

**File index:** A listing of folders and files included in the data set. Explain what files will be found in each folder and naming conventions used. Additional files could include any questionnaires or other survey instruments used to collect the data. Be sure to include codebooks and data dictionaries or similar README files.

See http://www.fs.usda.gov/rds/archive/products/RDS-2013-0013/\_fileindex_RDS-2013-0013.html

**File format/s:** What type/s of files are these? Are there multiple formats? What software is needed to use the file/s?

11. *(If you have time)* Share this directory with a neighbour as a zip file and see if you can each open and work with each other's project
