# Dataset Template

Format taken from Cohen et al.'s^1^ GitHub [page](www.github.com/viralemergence/datacov), look at their README for examples of how to fill in each section. If you have more complex datasets, you should consider more formal types of metadata documentation (see resources (LINK) for more info).

------------------------------------------------------------------------

## Dataset Title:

## DOI:

## Description of what repository contains:

------------------------------------------------------------------------

### Suggested citation:

Please cite \[\] when using the data/script in this repository.

### What's in the dataset

Describe each row of the dataset, and provide a description of what each column is referring to.

| column name | description |
|-------------|-------------|
|             |             |
|             |             |
|             |             |

^1^ Lily E. Cohen, Anna C. Fagre, Binqi Chen, Colin J. Carlson, and Daniel J. Becker. (2022) **datacov: An open database of bat coronavirus surveillance (1996 to 2018).** version 0.1. Copied README format from [www.github.com/viralemergence/datacov](http://www.github.com/viralemergence/datacov) on (June 6, 2023). DOI: 10.5281/zenodo.6644163.
