# Based on usethis::use_github_action('pkgdown'), providing below workflow
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

# Edits:
# rename to quarto-render-pages.yml
# use render, publish from https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-07-publish-single-format.md

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: quarto-render-pages

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto --version

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

- name: Render project
  uses: quarto-dev/quarto-actions/render@v2
  with:
    to: html

- name: Publish HTML
    uses: quarto-dev/quarto-actions/publish@v2
  with:
    target: gh-pages
    render: false